# --- Central-V specific parameters ---

action_selector: "soft_policies"
mask_before_softmax: True

runner: "episode_meta"

buffer_size: 100
batch_size_run: 1
batch_size: 100

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval_or_tau: 100

lr: 0.0005
num_tasks: 50 #max task is 50
lr_meta: 0.0005

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

agent_output_type: "pi_logits"
learner: "actor_critic_learner_meta"
entropy_coef: 0.01
use_rnn: True
standardise_returns: False
standardise_rewards: False
q_nstep: 5 # 1 corresponds to normal r + gammaV
critic_type: "cv_critic"

name: "maa2c_meta"

t_max: 2500000
