exclude: null
grid-search:
  "--config":
    - "mappo"

  lr:
    - 0.0001
    - 0.001
    - 0.0003
    - 0.0005

  standardise_rewards:
    - False

  use_rnn:
    - True

  target_update_interval_or_tau:
    - 200
    - 0.01
    - 0

  hidden_dim:
    - 64
    - 128

  t_max:
    - 2050000
  test_nepisode:
    - 100
  test_interval:
    - 25000
  log_interval:
    - 25000
  save_model_interval:
    - 50000
  save_model:
    - false

grid-search-groups:
  env0:
    - "--env-config": "gymma"
    - env_args.key: gym-mdde:Mdde-V0
    - env_args.time_limit: 25
